Repository ecency/ecency-vision, pull requests merged in 2023-09, with the labels that each got.

#1447 Emojis 2.0
  package.json
  src/common/components/decks/deck-settings/decks-settings.tsx
  src/common/components/decks/deck-threads-form/deck-threads-form-emoji-picker.tsx
  src/common/components/editor-toolbar/index.tsx
  src/common/components/emoji-picker/_index-old.scss
  src/common/components/emoji-picker/_index.scss
  src/common/components/emoji-picker/index-old.tsx
  src/common/components/emoji-picker/index.spec.tsx
  src/common/components/emoji-picker/index.tsx
  src/common/core/react-query.ts
  yarn.lock
Labels: enhancement

#1458 Deck 2.0: Fixed missed undefined checking
  src/common/components/emoji-picker/index.tsx
  src/common/components/entry-votes/index.tsx
Labels: bug

#1459 Fixed undefined error
  src/common/components/discussion/index.tsx
  src/common/components/entry-votes/index.tsx
  src/common/pages/entry/index-amp.tsx
  src/common/pages/entry/index.tsx
Labels: bug

#1461 Bugfix/app crash
  src/common/api/operations.ts
  src/common/components/comment/__snapshots__/index.spec.tsx.snap
  src/common/components/discussion/__snapshots__/test1.spec.tsx.snap
  src/common/components/entry-menu/menu-items-generator.ts
  src/common/components/video-upload-threespeak/index.tsx
  src/common/components/video-upload-threespeak/video-upload-item.tsx
  src/common/helper/posting.ts
  src/common/pages/community-functional.tsx
  src/common/pages/submit/api/publish.ts
Labels: bug

#1463 Video recorder: Added mimetype fallback
  src/common/components/video-upload-threespeak/video-upload-recorder.tsx
Labels: enhancement

#1464 3speak: added thumbs proxy in a gallery
  src/common/components/video-gallery/video-gallery-item.tsx
Labels: enhancement

#1452 Added claiming to RC modal
  src/common/api/mutations.ts
  src/common/api/operations.ts
  src/common/components/claim-account-credit/index.scss
  src/common/components/claim-account-credit/index.tsx
  src/common/components/key-or-hot/index.tsx
  src/common/components/rc-info/_index.scss
  src/common/components/rc-info/index.tsx
  src/common/helper/user-token.ts
  src/common/i18n/locales/en-US.json
Labels: enhancement

#1465 Bugfix/submit screen
  package.json
  src/common/api/private-api.ts
  src/common/components/beneficiary-editor/index.tsx
  src/common/components/emoji-picker/index.tsx
  src/common/components/video-gallery/index.scss
  src/common/components/video-gallery/index.tsx
  src/common/components/video-gallery/video-gallery-item.tsx
  src/common/core/react-query.ts
  src/common/i18n/locales/en-US.json
  src/common/img/svg.tsx
  src/common/pages/submit-old.tsx
  src/common/pages/submit/_index.scss
  src/common/pages/submit/api/publish.ts
  src/common/pages/submit/api/save-draft.ts
  src/common/pages/submit/api/schedule.ts
  src/common/pages/submit/api/update.ts
  src/common/pages/submit/hooks/advanced-manager.ts
  src/common/pages/submit/hooks/three-speak-manager-context.ts
  src/common/pages/submit/hooks/three-speak-manager.tsx
  src/common/pages/submit/index.tsx
  src/common/pages/submit/submit-preview-content.tsx
  src/common/pages/submit/submit-video-attachments.tsx
  yarn.lock
Labels: bug, enhancement

#1467 Added 3speak old video migration from edit or draft
  src/common/pages/submit/hooks/three-speak-manager-context.ts
  src/common/pages/submit/hooks/three-speak-manager.tsx
  src/common/pages/submit/hooks/three-speak-migration-adapter.ts
  src/common/pages/submit/index.tsx
Labels: bug

#1470 Camera switching: fixed camera switching even if camera web recorder is broken
  src/common/components/video-upload-threespeak/video-upload-recorder-actions.tsx
  src/common/components/video-upload-threespeak/video-upload-recorder.tsx
Labels: bug

#1469 Emoji picker: changed global position to local
  src/common/components/editor-toolbar/index.tsx
  src/common/components/emoji-picker/_index.scss
  src/common/components/emoji-picker/index.tsx
Labels: bug
